language: generic
dist: trusty
sudo: true
if: tag IS present
cache:
  - pip
  - apt
env:
  global:
    # ACI_SECRET
    - secure: qshAZHH1BcRG0vTuFHOynKpFkHPhSXoFoSiad3LR1hToJDZM1pj+YkcF9qwNB8n+cj0KfOCKGjLgzH0vGmPTH2jEi2k5DHdFDpb7ZsLyF6jeL5BGYkhNWLha5epvurOcSRcqHPgE0NRTNAUHSSSwFL2PnbzgEihlYJEng7FjjnPS4FBTBHxU4SQGIe9t9azZfGNyLpkXnn26iNMKVE9jol6y4RnzXdA7lwssWTi5g/5lmyb5Q4++0O1W9rmDUEuQyvwHXudrRKK8x8qeTnsr1z2mC8MU4L3n/ThgG0pPCG81gze1s0lyDxMlH9RQrkR8NkCzAY5yXVUnvPuQbguKQi6ubn0bKAiVHibYB4V9YL+/d7K6Og+D+n4ZvWzeP/JgiIjh3k8l+y6YTxCq+VtDbxfTM6cZHuIy8HSZBbCZ3EnsmxOBwjw4SZeD3Vrzkqu1WRDsT0bS7l5CaAlhgMnNLguBfyWs3fXDZDtwrhIWn26ZNVWrVWtx+UsWcPoGpKyXPMdIHyymB9I1Yp+tEqIg80zK5gbX54SCskoepeE6lqhhX5Q3YO/iTByKpovALRlhJhVsOgjAyj4acTFqtOUCBKzM90Ebivbx9B8uN/i1QGNffUihMrI9658Vu0E8XmxZGRYVN817BFgK4p2akOrKirYi33JYK3bf/5l9aEPRvIk=
    - DEPLOY_BUCKET=taqtiqa.io
    - ARCH=amd64 ACI_NAME=$(basename $TRAVIS_REPO_SLUG) ACI_ORG=$(dirname $TRAVIS_REPO_SLUG)
    - DEBIAN_FRONTEND=noninteractive
  matrix:
    - BUILD_JOBS="'base-notebook' 'minimal-notebook'"
    - BUILD_JOBS="'scipy-notebook'"
    - BUILD_JOBS="'r-notebook'"
    - BUILD_JOBS="'tensorflow-notebook'"
    - BUILD_JOBS="'datascience-notebook'"
    - BUILD_JOBS="'pyspark-notebook'"
    - BUILD_JOBS="'all-spark-notebook'"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get upgrade -qq
  - sudo apt-get install python3 gdebi-core
  - export PATH=$PATH:$HOME/.local/bin
  - git clone https://github.com/taqtiqa/ci.git
  - cat ci/scripts/install-openssl.sh | sudo bash
  - cat ci/scripts/install-rkt.sh | bash
  - cat ci/scripts/install-awscli.sh | sudo -H bash
  - cat ./scripts/gen-keys.sh | sudo bash -s $TRAVIS_BRANCH
  - export PATH=$PATH:$HOME/.local/bin
before_script:
  - openssl aes-256-cbc -pass env:ACI_SECRET -in ./rkt-stacks-privatekeys.asc.enc -out ./rkt-stacks-privatekeys.asc -d -a
script:
  # Builds are silent+long so tickle the travis-ci log
  # https://github.com/travis-ci/travis-ci/issues/6934
  - export -f travis_wait 
  - travis_wait 120 sleep infinity &
  - cat ./rkt-jupyter.sh | sudo bash
  # Kill while loop (the last process executed in the background)
  #- kill $!
notifications:
  email:
    recipients:
      - coders@taqtiqa.com
    on_success: [always]
    on_failure: [always]