language: go
dist: trusty
sudo: true
if: tag IS present
cache:
  - pip
  - apt
go:
  - 1.9
env:
  global:
    # ACI_SECRET
    - secure: DsIMXMuoc3GwVxlPjffXR2FqYIM+mh4H4CMByOrolusY8hB8KOuZ4iS02hD9To1jZHKqWIDQGEHomfIw/nDQzfM/zyTsGltTrH4dnegNv+ICp94oNACZrUSgV3dI2h9eG5PH58rPq/F7W4/Zb+CZRxwrwFsjO7PI/PvRqGNX+Gza7codS7fVF6FEUiV/B6lGvrzRYsDbmCurarlgc4OdN/tTft7h18H2a130mwpVSEaueehZhLVmJn9AoZPp5+kyZsjjW2laHOrvUUoly6Hcld0ijxQ7pFfT0hFhhNWBaRvbF3D8FOrq+JOMRdoYM0A1U5phcmX45OwkVlQf0cW7Dq9onl2Lxcr1elmiTFKHs+w0e0yXZVwPoaZumOANdcszsLXZ+wBGKfNtBnOmlsVF6uNrF930yzUDSL/x8RnHuU3NX3p+zDDOIGilovRULJUyxyUC2vkJjhstSaSqqp7hyDyTJWN23EPolkIC6hyzvL+aVH1LCCjkw6lDZD1WisGUa36Hjs/AI3S2aVCf9Cwh7SUI8B8Pv3MhM3DU+0EnfKwHzOZXTetSYp3Z1ERP2oMODokZRhlh2VVRPcKID47xxD/Hl/cssDmjIS1McGby+7+AIDjNTooHClpXdULOPu4G88tpgC7dqi0HjM19P4ns/9JPr6t6BXeh1eohvnU1ud4=
    - DEPLOY_BUCKET=taqtiqa.io
    - ARCH=amd64 ACI_NAME=$(basename $TRAVIS_REPO_SLUG) ACI_ORG=$(dirname $TRAVIS_REPO_SLUG)
    - DEBIAN_FRONTEND=noninteractive
    - PATH=$HOME/gopath/bin:$HOME/.local/bin:$PATH
    - export GOROOT=$(go env GOROOT)
  matrix:
    - BUILD_JOBS="'base-notebook' 'minimal-notebook'"
    - BUILD_JOBS="'scipy-notebook'"
    - BUILD_JOBS="'r-notebook'"
    - BUILD_JOBS="'tensorflow-notebook'"
    - BUILD_JOBS="'datascience-notebook'"
    - BUILD_JOBS="'pyspark-notebook'"
    - BUILD_JOBS="'all-spark-notebook'"
before_install:
  - export PATH=$HOME/gopath/bin:$HOME/.local/bin:$PATH
  - sudo apt-get update -qq
  # - sudo apt-get upgrade -qq
  - sudo apt-get install python3 gdebi-core
  - git clone https://github.com/taqtiqa/ci.git
  - cat ci/scripts/install-openssl.sh | sudo bash
  - cat ci/scripts/install-rkt.sh | bash
  - cat ci/scripts/install-skopeo.sh | sudo -E bash
  - cat ci/scripts/install-docker2aci.sh | sudo -E bash
  - cat ci/scripts/install-awscli.sh | sudo -H bash
  - cat ./scripts/gen-keys.sh | sudo bash -s $TRAVIS_BRANCH
before_script:
  - openssl aes-256-cbc -pass env:ACI_SECRET -in ./rkt-stacks-privatekeys.asc.enc -out ./rkt-stacks-privatekeys.asc -d -a
script:
  # Builds are silent+long so tickle the travis-ci log
  # https://github.com/travis-ci/travis-ci/issues/6934
  - export -f travis_wait 
  - travis_wait 120 sleep infinity &
  - cat ./rkt-jupyter.sh | sudo bash
notifications:
  email:
    recipients:
      - coders@taqtiqa.com
    on_success: [always]
    on_failure: [always]