language: generic
dist: trusty
sudo: true
if: tag IS present
env:
  global:
    - secure: Q9wzEBr9E/Evdd2HcK7X8F9wgDf3KXIhW/vxqHCIGwnbfiImAyHWGKhLQxKVK8lGma4N7KFN3S5dW5RcRWR2RlunA8ENdTuLlXSwQwygA197B6/CvsgE959steTMoDmX6QdBBLfDUDtx9zWUQPl5PbJ4A7mJrOU1vR6JpG7AzTUieQD7rK35b2SseoiwvxGaHoP2+JuSsCVIdvbFc67DjX8xKhdR7yKx7bzkXeja49ngiBYuS+LCArtMEltkJFoo/sr7TyqTqr/gxm4ZLWcJkHMgpxfmbhvURJhUcsMQbAKZeF3AWdwvILhKDQUyzNCOkx0lTJfeOHnACnfn/vtnMGTNs4lmCsspEEHaS/KKbNozTwIigjLXekx/t9YK46jTjmIL8PCoBFiCRmFH01NOArjRSZ0nwOrXFf8Hf12mXshr00DKxTWyeLmA4fqu7nc092WTyw4k3SKmFn7va64p8WXqlCusFo4LSMHCF1n/QMciubQNMaEvPCSexaTKUlDoV9aJ/jD+zeEohEEwj3D7r/5exnLSQS1zSRpKAusD4BMdlOZqc7reaWEiRpA8eyTjbXwr6YebemLKNhIDIhn6tnioNXcyZBD8odn2B5PLSLLYH7zvJL2dpvquzumaDQTguOO3w1Z3QsiohC4sdqEXT1W/Pvy8x5usZt30dsMq3wg=
    - ARTIFACTS_KEY=${AWS_ACCESS_KEY_ID}
    - ARTIFACTS_SECRET=${AWS_SECRET_ACCESS_KEY}
    - ARTIFACTS_BUCKET=taqtiqa.io
  matrix:
    - ARCH=amd64 ACI_NAME=$(basename $TRAVIS_REPO_SLUG) ACI_ORG=$(dirname $TRAVIS_REPO_SLUG)
before_install:
  - apt-get update -qq
  - apt-get install -qq rkt
  - git clone https://github.com/taqtiqa/ci.git
  - cat ci/scripts/openssl.sh | sudo bash
before_script:
  - openssl aes-256-cbc -pass env:ACI_SECRET -in ./rkt-stacks-privatekeys.asc.enc -out ./rkt-stacks-privatekeys.asc -d -a
script:
  - cat ./rkt-jupyter.sh | sudo bash
after_success:
  - rm -rf ./ci
  - export ARTIFACTS_PATHS="$(git ls-files -o | tr \"\\n\" \":\")"
  - echo $ARTIFACTS_PATHS
addons:
  artifacts:
    s3_region: "us-east-1" 
    paths:
    - $(git ls-files -o | tr "\n" ":") 
    debug: true
    target_paths:
    - /aci
notifications:
  email:
    recipients:
      - coders@taqtiqa.com
    on_success: [always]
    on_failure: [always]